# Generated by Django 5.2.7 on 2026-02-16 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hero_Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_text_title', models.CharField(max_length=100)),
                ('hero_text_body', models.TextField()),
                ('hero_image', models.ImageField(upload_to='main/images/')),
            ],
        ),
    ]
