# Generated by Django 5.2.7 on 2026-02-17 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_title', models.CharField(max_length=60)),
                ('service_description', models.TextField(max_length=1000)),
            ],
        ),
        migrations.AlterField(
            model_name='hero_section',
            name='hero_text_body',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='hero_section',
            name='hero_text_title',
            field=models.CharField(max_length=60),
        ),
    ]
