# Generated by Django 5.2.7 on 2026-02-18 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_service_alter_hero_section_hero_text_body_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_description',
            field=models.TextField(max_length=4000),
        ),
    ]
