# Generated by Django 5.2.7 on 2026-02-19 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_team_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero_section',
            name='hero_image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
