# Generated by Django 5.2.7 on 2026-02-19 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_hero_section_hero_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team_member',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
