# Generated by Django 5.2.7 on 2026-02-21 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_team_member_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='service_icon',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='service',
            name='service_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
