# Generated by Django 5.2.7 on 2026-02-22 02:37

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_service_service_icon_service_service_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero_section',
            name='hero_image',
            field=models.ImageField(upload_to=main.models.image_upload_path),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_icon',
            field=models.ImageField(blank=True, null=True, upload_to=main.models.image_upload_path),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_image',
            field=models.ImageField(blank=True, null=True, upload_to=main.models.image_upload_path),
        ),
        migrations.AlterField(
            model_name='team_member',
            name='image',
            field=models.ImageField(upload_to=main.models.image_upload_path),
        ),
    ]
