# Generated by Django 5.2.7 on 2026-02-22 11:29

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_hero_section_hero_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='why_us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('why_us_icon', models.ImageField(upload_to=main.models.image_upload_path)),
                ('why_us_title', models.TextField(max_length=50)),
                ('why_us_desc', models.TextField(max_length=500)),
            ],
        ),
    ]
