# Generated by Django 5.2.7 on 2026-02-22 12:29

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_why_us'),
    ]

    operations = [
        migrations.CreateModel(
            name='About_Us_Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_hero_text_title', models.CharField(max_length=60)),
                ('about_hero_text_body', models.TextField(max_length=300)),
                ('about_hero_image', models.ImageField(upload_to=main.models.image_upload_path)),
            ],
        ),
    ]
