# Generated by Django 5.2.7 on 2026-02-22 13:34

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_about_us_hero'),
    ]

    operations = [
        migrations.CreateModel(
            name='Our_Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_icon', models.ImageField(blank=True, null=True, upload_to=main.models.image_upload_path)),
                ('product_title', models.CharField(max_length=50)),
                ('product_description', models.TextField(max_length=500)),
            ],
        ),
    ]
