# Generated by Django 5.2.7 on 2026-02-25 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_our_products'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Our_Products',
        ),
        migrations.AddField(
            model_name='hero_section',
            name='honey_pot',
            field=models.CharField(default='hello', max_length=20),
            preserve_default=False,
        ),
    ]
