# Generated by Django 5.2.7 on 2026-02-25 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_delete_our_products_hero_section_honey_pot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hero_section',
            old_name='honey_pot',
            new_name='madatory_field',
        ),
    ]
