# Generated by Django 5.2.7 on 2026-02-25 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_rename_honey_pot_hero_section_madatory_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='mandatory_field',
            field=models.CharField(default='hello', max_length=20),
            preserve_default=False,
        ),
    ]
