# Generated by Django 5.2.7 on 2026-02-25 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_service_mandatory_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='about_us_hero',
            name='madatory_field',
            field=models.CharField(default='hello', max_length=20),
            preserve_default=False,
        ),
    ]
