# Generated by Django 5.2.7 on 2026-02-25 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_about_us_hero_madatory_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='team_member',
            name='mandatory_field',
            field=models.CharField(default='hello', max_length=20),
            preserve_default=False,
        ),
    ]
