# Generated by Django 5.2.7 on 2026-02-25 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_team_member_mandatory_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='why_us',
            name='mandatory_field',
            field=models.CharField(default='hello', max_length=20),
            preserve_default=False,
        ),
    ]
