# Generated by Django 5.2.7 on 2026-02-25 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_contact_us'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about_us_hero',
            old_name='madatory_field',
            new_name='mandatory_field',
        ),
        migrations.RenameField(
            model_name='hero_section',
            old_name='madatory_field',
            new_name='mandatory_field',
        ),
    ]
