# Generated by Django 5.2.7 on 2026-02-26 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_rename_madatory_field_about_us_hero_mandatory_field_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero_section',
            name='mandatory_field',
            field=models.CharField(),
        ),
    ]
