# Generated by Django 5.2.7 on 2026-02-26 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_alter_hero_section_mandatory_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero_section',
            name='mandatory_field',
            field=models.CharField(blank=True, default='hello', max_length=20),
            preserve_default=False,
        ),
    ]
