# Generated by Django 5.2.7 on 2026-02-26 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_alter_hero_section_mandatory_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero_section',
            name='hero_text_body',
            field=models.TextField(max_length=600),
        ),
        migrations.AlterField(
            model_name='hero_section',
            name='hero_text_title',
            field=models.CharField(max_length=100),
        ),
    ]
