# Generated by Django 5.2.7 on 2026-02-26 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_alter_hero_section_hero_text_body_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero_section',
            name='hero_text_body',
            field=models.TextField(max_length=650),
        ),
        migrations.AlterField(
            model_name='hero_section',
            name='hero_text_title',
            field=models.CharField(max_length=110),
        ),
    ]
