# Generated by Django 5.2.7 on 2026-02-26 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_alter_hero_section_hero_text_body_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about_us_hero',
            name='about_hero_text_body',
            field=models.TextField(max_length=650),
        ),
        migrations.AlterField(
            model_name='about_us_hero',
            name='about_hero_text_title',
            field=models.CharField(max_length=110),
        ),
        migrations.AlterField(
            model_name='about_us_hero',
            name='mandatory_field',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
