# Generated by Django 5.2.7 on 2026-02-26 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_alter_about_us_hero_about_hero_text_body_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='mandatory_field',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_description',
            field=models.TextField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_title',
            field=models.CharField(max_length=110),
        ),
    ]
