# Generated by Django 5.2.7 on 2026-02-26 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_alter_service_mandatory_field_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team_member',
            name='instagram_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='team_member',
            name='linkedin_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='team_member',
            name='mandatory_field',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='team_member',
            name='name',
            field=models.CharField(max_length=35),
        ),
        migrations.AlterField(
            model_name='team_member',
            name='position',
            field=models.CharField(max_length=35),
        ),
        migrations.AlterField(
            model_name='team_member',
            name='twitter_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
