# Generated by Django 5.2.7 on 2026-02-26 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_alter_team_member_instagram_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='why_us',
            name='mandatory_field',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='why_us',
            name='why_us_title',
            field=models.TextField(max_length=60),
        ),
    ]
